name: Bootloader lock debug

on:
  push:

jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imc-unknown-none-elf
          components: rust-src
      - run: cd bootloader/esp && cargo check --release --features esp32c3 --target riscv32imc-unknown-none-elf
      - name: Print generated lock
        if: always()
        run: cat bootloader/esp/Cargo.lock
